[application]
name = "mime"
default_platform = "desktop"

[web.app]
title = "Mime - Notes"
base_path = "mime"

[web.resource]
style = ["/assets/main.css"]
script = []

[web.resource.dev]
style = []
script = []

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[bundle]
identifier = "com.mime.app"
publisher = "Mime"
icon = ["assets/icons/icon.png", "assets/icons/icon.icns"]

[desktop]
always_on_top = false

